---

- hosts: all
  become: true
  tasks:

  -  name: Update repositories and install apache and php packages
     package:
       name:
         - "{{ apache_package }}"
         - "{{ php_package }}"
       state: latest
       update_cache: yes
